version: '3.8'

services:
  compiler:
    image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    command: make DEBUG=1
    volumes:
      - "./ledger-app-ergo:/app"
  emulator:
    image: ghcr.io/ledgerhq/speculos:latest
    command: "apps/ergo.elf --apdu-port 40000 --vnc-port 41000 --display headless"
    ports:
      - 1234:1234 # gdb
      - 5000:5000 # api
      - 40000:40000 # apdu
      - 41000:41000 # vnc
    volumes:
      - "./ledger-app-ergo/bin/app.elf:/speculos/apps/ergo.elf"
